import json
import argparse, os

def write_meta(sentence_file, label_file, output_file):

    sentences = [sentence.rstrip('\n') for sentence in open(sentence_file)]

    with open(label_file, 'r') as f:
        labels = json.load(f) # from labels generated by clustering

    meta = ['Sentence\tLabel\n']
    meta.extend([s + '\t' + str(l) + '\n' for s, l in zip(sentences, labels)])
    
    with open(output_file, 'w') as f:
        f.writelines(meta)
